- hosts: slave
  tasks:
   - include_vars: "/root/automate/nnip.yml"
   - file: 
        path: "/data"
        state: directory
        mode: 0755
 
   - replace:
        path: "/etc/hadoop/hdfs-site.xml"
        regexp: "</configuration>"
        replace: "<property>\n<name>dfs.data.dir</name>\n<value>/data</value>\n</property>\n\n</configuration>"

   - replace:
        path: "/etc/hadoop/core-site.xml"
        regexp: "</configuration>"
        replace: "<property>\n<name>fs.default.name</name>\n<value>hdfs://{{ ip }}:9001</value>\n</property>\n\n</configuration>"

   - command: "iptables -F"

   - command: "hadoop-daemon.sh start datanode"

