- hosts: jt
  tasks:
   - include_vars: "/root/automate/jtip.yml"

   - include_vars: "/root/automate/nnip.yml"

   - replace:
        path: "/etc/hadoop/mapred-site.xml"
        regexp: "</configuration>"
        replace: "<property>\n<name>mapred.job.tracker</name>\n<value>{{ jtip }}:9002</value>\n</property>\n\n</configuration>"

   - replace:
        path: "/etc/hadoop/core-site.xml"
        regexp: "</configuration>"
        replace: "<property>\n<name>fs.default.name</name>\n<value>hdfs://{{ ip }}:9001</value>\n</property>\n\n</configuration>"

   - command: "iptables -F"

   - command: "hadoop-daemon.sh start jobtracker"

